---
apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
product: k3d
k3d:
  v1alpha5Simple:
    agents: 3
    image: docker.io/rancher/k3s:v1.30.4-k3s1
    options:
      k3s:
        extraArgs:
          - arg: --disable=traefik
            nodeFilters:
              - server:0
    # Simulate a multi-node cluster with NFS, in production you would use a real NFS server for ollama LLMs
    volumes:
      - volume: nfs:/nfs
        nodeFilters:
          - server:0
          - agent:*
